# Site settings
title: Rachel Cantor
email: rachelcantor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, World!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iheartcake.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
